language: julia

julia:
  - 1.1
  - 1

os:
  - linux

sudo: false
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libblas-dev

matrix:
 allow_failures:
 - julia: nightly

notifications:
  email: false
